# Generated by Django 5.1.4 on 2024-12-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
