# Generated by Django 5.1.4 on 2024-12-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_offer_price_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.FileField(default=100, upload_to=''),
            preserve_default=False,
        ),
    ]
