# Generated by Django 5.1.4 on 2025-01-02 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='cart',
        ),
        migrations.AddField(
            model_name='buy',
            name='qty',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='total_price',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
