# Generated by Django 5.1.4 on 2025-01-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_buy_cart_buy_qty_buy_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
