# Generated by Django 5.1.4 on 2025-01-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_buy_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], default='cod', max_length=10),
        ),
    ]
